spring:
  profiles:
    active: dev


---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Saket
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'  config:    activate:      on-profile: dev

---

spring:
  datasource:
    url: jdbc:h2:mem:dcbapp
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:    activate:      on-profile: qa      
